spring:
  datasource:
    url: jdbc:mysql://mysql_board:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      #ddl-auto: create
      #ddl-auto: validate
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    time-zone: Asia/Seoul

server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: kim00920-s3-bucket
    region:
      static: ap-southeast-2
    stack:
      auto: false

